domain_path: C:\Users\liuzh\Desktop\AD9238\vitis_files\ad9238\AD9238_platform\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: E:\Work\2025.1\Vitis\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
