domain_path: C:\Users\liuzh\Desktop\AD9238\vitis_files\ad9238_ps\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: E:\Work\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
