set_property PACKAGE_PIN U11 [get_ports clk_out1_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out1_0]
set_property PACKAGE_PIN U12 [get_ports {ch1_din_0[0]}]
set_property PACKAGE_PIN U9 [get_ports {ch1_din_0[1]}]
set_property PACKAGE_PIN U10 [get_ports {ch1_din_0[2]}]
set_property PACKAGE_PIN Y10 [get_ports {ch1_din_0[3]}]
set_property PACKAGE_PIN Y11 [get_ports {ch1_din_0[4]}]
set_property PACKAGE_PIN W7 [get_ports {ch1_din_0[5]}]
set_property PACKAGE_PIN V7 [get_ports {ch1_din_0[6]}]
set_property PACKAGE_PIN Y5 [get_ports {ch1_din_0[7]}]
set_property PACKAGE_PIN Y6 [get_ports {ch1_din_0[8]}]
set_property PACKAGE_PIN U5 [get_ports {ch1_din_0[9]}]
set_property PACKAGE_PIN U6 [get_ports {ch1_din_0[10]}]
set_property PACKAGE_PIN V4 [get_ports {ch1_din_0[11]}]
set_property PACKAGE_PIN V5 [get_ports ch1_otr_0]
set_property IOSTANDARD LVCMOS33 [get_ports ch1_otr_0]
set_property IOSTANDARD LVCMOS33 [get_ports {ch1_din_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ch1_din_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ch1_din_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ch1_din_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ch1_din_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ch1_din_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ch1_din_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ch1_din_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ch1_din_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ch1_din_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ch1_din_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ch1_din_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports data_drop_0]
set_property PACKAGE_PIN P20 [get_ports data_drop_0]
set_property PACKAGE_PIN P21 [get_ports m00_axi_txn_done_0]
set_property PACKAGE_PIN H18 [get_ports start_btn_0]
set_property IOSTANDARD LVCMOS33 [get_ports m00_axi_txn_done_0]
set_property IOSTANDARD LVCMOS33 [get_ports start_btn_0]
set_property IOSTANDARD LVCMOS33 [get_ports aux_reset_in_0]
set_property DRIVE 16 [get_ports clk_out1_0]


set_property IOSTANDARD LVCMOS33 [get_ports SYS_CLK_50M]
set_property PACKAGE_PIN Y9 [get_ports SYS_CLK_50M]
set_property PACKAGE_PIN H19 [get_ports aux_reset_in_0]


set_property package_pin R20 [get_ports {all_done_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {all_done_tri_io[0]}]
set_property OFFCHIP_TERM NONE [get_ports all_done_tri_io[0]]
set_property SLEW SLOW [get_ports {all_done_tri_io[0]}]
